databases:
  - name: THE BEST UDON_DB
    databaseName: the best udon_db
    user: THE BEST UDON
    region: singapore

services:
  - type: web
    name: THE BEST UDON
    env: ruby
    region: singapore
    plan: free
    buildCommand: apt-get update && apt-get install -y libyaml-dev
                  bundle install
                  yarn install
                  bundle exec rake assets:precompile
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: THE BEST UDON_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

